service: store
image: verashkt/store
servers:
  web:
    - 84.54.31.190
registry:
  username: verashkt
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] %>
builder:
  arch: amd64
proxy:
  ssl: true
  host: app.example.com

